### ISSUE TITLE
Widget not working in Mx 6.9.0

### ISSUE THREAD

**Issue by JordyDelahaije** [Andries-Smit/TabExtension#6] opened 2016-10-07 12:48 UTC
Hello,

I've implemented this widget into my project at 6.6.0 and at the time it worked fine. However after upgrading to Mx 6.9.0 the widget doesn't work anymore.

When opening the tab page on which this widget is positioned I can see the following message:
Could not create widget mxui.widget.DataView: TypeError: Cannot read property 'parentNode' of null

Regards,
Jordy Delahaije

**Comment by davelina** [comment] 2016-10-10 13:40
Hello, 

I can confirm this issue. Even the simplest of projects are resulting in this error, thus something changed in the way Mendix is loading this widget? 

Regards, 
Dave Lina

**Comment by jrvdberg** [comment] 2016-10-25 13:59
Hello, another confirmation of this issue. Are you working on a way to resolve this or should we look for an alternative? 

Kind regards, 
Rob

**Comment by alex-lv** [comment] 2016-12-06 15:24
Hi

I am getting this issue in 6.9.1 

_Could not create widget mxui.widget.DataView: TypeError: Cannot read property 'parentNode' of null_

Shame as it looks like an awesome widget. :)

Thanks
Alex

**Comment by hganzeboom** [comment] 2016-12-08 13:01
Same issue here with Mendix 6.10.0: Could not create widget mxui.widget.DataView

Could you please let us know it this will be fixed in the near future?

**Comment by Andries-Smit** [comment] 2016-12-09 10:50
We will update the widget for the latest Mendix.

**Comment by hganzeboom** [comment] 2016-12-09 13:54
Thank you for the update!

**Comment by Andries-Smit** [comment] 2016-12-09 17:18
Just created new release 3.0. 
[https://github.com/Andries-Smit/TabExtension/releases/download/3.0/TabExtension.mpk](https://github.com/Andries-Smit/TabExtension/releases/download/3.0/TabExtension.mpk)

Please let me know if this fixes your issue. After that I will update it in the app store.

**Comment by hganzeboom** [comment] 2016-12-12 07:50
It works now! Thank you very much!!

**Comment by alex-lv** [comment] 2016-12-20 12:59
Hi Andries

Apologies for the delay – all good, it works fine now.

Many thanks

Alex

**Closed** 2018-07-04 13:45 UTC
